services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1
    container_name: pocket-id
    restart: unless-stopped
    volumes:
      - "./data:/app/data"
    environment:
      - TRUST_PROXY=false
      - MAXMIND_LICENSE_KEY=
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
