networks:
  caddy_net:
    driver: bridge
    name: caddy_network

services:
  caddy-proxy:
    networks:
      caddy_net:
    labels:
      caddy: "*.${HOSTNAME}"
      caddy.tls.dns: duckdns ${DUCKDNS_TOKEN}
      # caddy: (tinyauth_forwarder)
      # caddy.forward_auth: tinyauth:3000
      # caddy.forward_auth.uri: /api/auth/caddy

  homepage:
    networks:
      - caddy_net
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_SUBDOMAIN}
    labels:
      caddy: ${HOMEPAGE_SUBDOMAIN}
      caddy.reverse_proxy: "{{upstreams 3000}}"

  actual-server:
    networks:
      - caddy_net
    labels:
      caddy: ${ACTUAL_SUBDOMAIN}
      caddy.reverse_proxy: "{{upstreams 5006}}"
      homepage.group: Budget
      homepage.name: Actual Budget
      homepage.icon: actual-budget
      homepage.href: http://${ACTUAL_SUBDOMAIN}
      homepage.description: App for managing finances
      homepage.showStats: true

  pocket-id:
    networks:
      - caddy_net
    environment:
      - TRUST_PROXY=true
      - APP_URL=https://${POCKETID_SUBDOMAIN}
    labels:
      caddy: ${POCKETID_SUBDOMAIN}
      caddy.reverse_proxy: "{{upstreams 1411}}"
      homepage.group: Auth
      homepage.name: Pocket ID
      homepage.icon: pocket-id
      homepage.href: http://${POCKETID_SUBDOMAIN}
      homepage.description: A simple OIDC provider for passwordless authentication.
      homepage.showStats: true

  tinyauth:
    networks:
      - caddy_net
    environment:
      - SECRET=${TINYAUTH_SECRET}
      - APP_URL=https://${TINYAUTH_SUBDOMAIN}
      - GENERIC_CLIENT_ID=${TINYAUTH_GENERIC_CLIENT_ID}
      - GENERIC_CLIENT_SECRET=${TINYAUTH_GENERIC_CLIENT_SECRET}
      - GENERIC_AUTH_URL=https://${POCKETID_SUBDOMAIN}/authorize
      - GENERIC_TOKEN_URL=https://${POCKETID_SUBDOMAIN}/api/oidc/token
      - GENERIC_USER_URL=https://${POCKETID_SUBDOMAIN}/api/oidc/userinfo
      - GENERIC_SCOPES=openid,email,profile,groups
      - GENERIC_NAME=Pocket ID
      - OAUTH_AUTO_REDIRECT=generic
      - GENERIC_SKIP_SSL=true
    labels:
      caddy: ${TINYAUTH_SUBDOMAIN}
      caddy.reverse_proxy: "{{upstreams 3000}}"

  immich-server:
    networks:
      - caddy_net
    labels:
      caddy: ${IMMICH_SUBDOMAIN}
      caddy.reverse_proxy: "{{upstreams 2283}}"
      homepage.group: Media
      homepage.name: Immich
      homepage.icon: immich
      homepage.href: http://${IMMICH_SUBDOMAIN}
      homepage.description: Self-hosted photo and video management solution.
      homepage.showStats: true
      homepage.widget.type: immich
      homepage.widget.url: https://${IMMICH_SUBDOMAIN}
      homepage.widget.key: ${IMMICH_KEY_API}
      homepage.widget.version: 2

  spoolman:
    networks:
      - caddy_net
    labels:
      caddy: ${SPOOLMAN_SUBDOMAIN}
      caddy.reverse_proxy: "{{upstreams 8000}}"
      homepage.group: 3D Printing
      homepage.name: Spoolman
      homepage.icon: spoolman
      homepage.href: http://${SPOOLMAN_SUBDOMAIN}
      homepage.description: Keep track of your inventory of 3D-printer filament spools.
      homepage.showStats: true
      homepage.widget.type: spoolman
      homepage.widget.url: https://${SPOOLMAN_SUBDOMAIN}

  # manyfold:
  #   networks:
  #     - caddy_net
  #   labels:
  #     caddy: ${MANYFOLD_SUBDOMAIN}
  #     caddy.reverse_proxy: "{{upstreams 3214}}"
  #     homepage.group: 3D Printing
  #     homepage.name: Manyfold
  #     homepage.icon: manyfold
  #     homepage.href: http://${MANYFOLD_SUBDOMAIN}
  #     homepage.description: Organise and share your 3d print files.
  #     homepage.showStats: true

  vaultwarden:
    networks:
      - caddy_net
    environment:
      DOMAIN: https://${VAULTWARDEN_SUBDOMAIN}
    labels:
      caddy: ${VAULTWARDEN_SUBDOMAIN}
      caddy.reverse_proxy: "{{upstreams 80}}"
      homepage.group: Auth
      homepage.name: Vaultwarden
      homepage.icon: vaultwarden
      homepage.href: http://${VAULTWARDEN_SUBDOMAIN}
      homepage.description: Access your sensitive information on any device with secure cloud sync.
      homepage.showStats: true

  grafana:
    networks:
      - caddy_net
    environment:
      - GF_SERVER_ROOT_URL=https://${GRAFANA_SUBDOMAIN}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${GRAFANA_GENERIC_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GRAFANA_GENERIC_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://${POCKETID_SUBDOMAIN}/authorize
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://${POCKETID_SUBDOMAIN}/api/oidc/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://${POCKETID_SUBDOMAIN}/api/oidc/userinfo
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid,email,profile,groups
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_USE_REFRESH_TOKEN=true
    labels:
      caddy: ${GRAFANA_SUBDOMAIN}
      caddy.reverse_proxy: "{{upstreams 3000}}"
      homepage.group: Analytics
      homepage.name: Grafana
      homepage.icon: grafana
      homepage.href: http://${GRAFANA_SUBDOMAIN}
      homepage.description: Grafana is an analytics and interactive visualization web application.
      homepage.showStats: true
