networks:
  caddy_net:
    driver: bridge
    name: caddy_network
    ipam:
      config:
        - subnet: ${SUBNET_IP}

services:
  caddy:
    networks:
      caddy_net:
    environment:
      HOST: ${HOSTNAME}
      CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN}

  homepage:
    networks:
      - caddy_net
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_SUBDOMAIN}

  actual-server:
    networks:
      - caddy_net
    environment:
      ACTUAL_OPENID_DISCOVERY_URL: https://${POCKETID_SUBDOMAIN}/.well-known/openid-configuration
      ACTUAL_OPENID_CLIENT_ID: ${ACTUAL_CLIENT_ID}
      ACTUAL_OPENID_CLIENT_SECRET: ${ACTUAL_CLIENT_SECRET}
      ACTUAL_OPENID_SERVER_HOSTNAME: https://${ACTUAL_SUBDOMAIN}
      ACTUAL_OPENID_ENFORCE: true
      ACTUAL_TOKEN_EXPIRATION: openid-provider
    labels:
      homepage.group: Budget
      homepage.name: Actual Budget
      homepage.icon: actual-budget
      homepage.href: http://${ACTUAL_SUBDOMAIN}
      homepage.description: App for managing finances
      homepage.showStats: true

  pocket-id:
    networks:
      - caddy_net
    environment:
      - TRUST_PROXY=true
      - APP_URL=https://${POCKETID_SUBDOMAIN}
    labels:
      homepage.group: Auth
      homepage.name: Pocket ID
      homepage.icon: pocket-id
      homepage.href: http://${POCKETID_SUBDOMAIN}
      homepage.description: A simple OIDC provider for passwordless authentication.
      homepage.showStats: true

  tinyauth:
    networks:
      - caddy_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET=${TINYAUTH_SECRET}
      - APP_URL=https://${TINYAUTH_SUBDOMAIN}
      - GENERIC_CLIENT_ID=${TINYAUTH_GENERIC_CLIENT_ID}
      - GENERIC_CLIENT_SECRET=${TINYAUTH_GENERIC_CLIENT_SECRET}
      - GENERIC_AUTH_URL=https://${POCKETID_SUBDOMAIN}/authorize
      - GENERIC_TOKEN_URL=https://${POCKETID_SUBDOMAIN}/api/oidc/token
      - GENERIC_USER_URL=https://${POCKETID_SUBDOMAIN}/api/oidc/userinfo
      - GENERIC_SCOPES=openid,email,profile,groups
      - GENERIC_NAME=Pocket ID
      - OAUTH_AUTO_REDIRECT=generic

  immich-server:
    networks:
      - caddy_net
    labels:
      homepage.group: Media
      homepage.name: Immich
      homepage.icon: immich
      homepage.href: http://${IMMICH_SUBDOMAIN}
      homepage.description: Self-hosted photo and video management solution.
      homepage.showStats: true
      homepage.widget.type: immich
      homepage.widget.url: https://${IMMICH_SUBDOMAIN}
      homepage.widget.key: ${IMMICH_KEY_API}
      homepage.widget.version: 2

  spoolman:
    networks:
      - caddy_net
    labels:
      tinyauth.oauth.groups: spoolman
      tinyauth.ip.bypass: ${SUBNET_IP}
      homepage.group: 3D Printing
      homepage.name: Spoolman
      homepage.icon: spoolman
      homepage.href: http://${SPOOLMAN_SUBDOMAIN}
      homepage.description: Keep track of your inventory of 3D-printer filament spools.
      homepage.showStats: true
      homepage.widget.type: spoolman
      homepage.widget.url: https://${SPOOLMAN_SUBDOMAIN}

  # manyfold:
  #   networks:
  #     - caddy_net
  #   labels:
  #     homepage.group: 3D Printing
  #     homepage.name: Manyfold
  #     homepage.icon: manyfold
  #     homepage.href: http://${MANYFOLD_SUBDOMAIN}
  #     homepage.description: Organise and share your 3d print files.
  #     homepage.showStats: true

  vaultwarden:
    networks:
      - caddy_net
    environment:
      DOMAIN: https://${VAULTWARDEN_SUBDOMAIN}
    labels:
      homepage.group: Auth
      homepage.name: Vaultwarden
      homepage.icon: vaultwarden
      homepage.href: http://${VAULTWARDEN_SUBDOMAIN}
      homepage.description: Access your sensitive information on any device with secure cloud sync.
      homepage.showStats: true

  grafana:
    networks:
      - caddy_net
    environment:
      - GF_SERVER_ROOT_URL=https://${GRAFANA_SUBDOMAIN}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${GRAFANA_GENERIC_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GRAFANA_GENERIC_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://${POCKETID_SUBDOMAIN}/authorize
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://${POCKETID_SUBDOMAIN}/api/oidc/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://${POCKETID_SUBDOMAIN}/api/oidc/userinfo
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid,email,profile,groups
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_USE_REFRESH_TOKEN=true
    labels:
      homepage.group: Analytics
      homepage.name: Grafana
      homepage.icon: grafana
      homepage.href: http://${GRAFANA_SUBDOMAIN}
      homepage.description: Grafana is an analytics and interactive visualization web application.
      homepage.showStats: true

  prometheus:
    networks:
      - caddy_net
    labels:
      tinyauth.ip.bypass: ${SUBNET_IP}
      tinyauth.oauth.groups: prometheus
      homepage.group: Analytics
      homepage.name: Prometheus
      homepage.icon: prometheus
      homepage.href: http://${PROMETHEUS_SUBDOMAIN}
      homepage.description: Prometheus is a systems and service monitoring system and time series database.
      homepage.showStats: true
      homepage.widget.type: prometheus
      homepage.widget.url: https://${PROMETHEUS_SUBDOMAIN}

  fresh-rss:
    networks:
      - caddy_net
    environment:
      OIDC_ENABLED: 1
      OIDC_CLIENT_ID: ${FRESHRSS_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${FRESHRSS_CLIENT_SECRET}
      OIDC_PROVIDER_METADATA_URL: https://${POCKETID_SUBDOMAIN}/.well-known/openid-configuration
      OIDC_SCOPES: openid email profile
      OIDC_X_FORWARDED_HEADERS: X-Forwarded-Proto X-Forwarded-Host
      OIDC_REMOTE_USER_CLAIM: preferred_username
    labels:
      homepage.group: News
      homepage.name: FreshRSS
      homepage.icon: freshrss
      homepage.href: http://${FRESHRSS_SUBDOMAIN}
      homepage.description: RSS feed aggregator.
      homepage.showStats: true
      homepage.widget.type: freshrss
      homepage.widget.url: https://${FRESHRSS_SUBDOMAIN}
      homepage.widget.username: ${FRESHRSS_USER}
      homepage.widget.password: ${FRESHRSS_PASSWORD}
