services:
  actual-server:
    image: docker.io/actualbudget/actual-server:latest-alpine
    container_name: actualbudget
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "node src/scripts/health-check.js"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
