services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    container_name: spoolman
    restart: unless-stopped
    volumes:
      - ./data:/home/app/.local/share/spoolman
    environment:
      TZ: Europe/Paris
      SPOOLMAN_METRICS_ENABLED: true
