services:
  vaultwarden:
    image: vaultwarden/server:latest-alpine
    container_name: vaultwarden
    restart: always
    environment:
      SIGNUPS_ALLOWED: "false"
    volumes:
      - ./data:/data
