global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: immich_api
    static_configs:
      - targets: ['immich-server:8081']

  - job_name: immich_microservices
    static_configs:
      - targets: ['immich-server:8082']

  - job_name: 'spoolman'
    static_configs:
      - targets: ['spoolman:8000']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
