services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "1000"
    volumes:
      - ./data:/var/lib/grafana
    environment:
      GF_SERVER_ENABLE_GZIP: true
